---
rbac:
  create: true

alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  ingress:
    enabled: true
    hosts:
      - test.troybebee.do.citopro.com 
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
    tls:
    - secretName: prometheus-tls
      hosts:
        - test.troybebee.do.citopro.com 
  
  persistentVolume:
    enabled: true
